import syltherineImg from "../../public/image 1.png";
import leviosaImg from "../../public/image 2.png";
import lolitoImg from "../../public/image 3.png";
import respiraImg from "../../public/image 4.png";
import muggoImg from "../../public/image 6.png";
import pingkyImg from "../../public/image 7.png";
import pottyImg from "../../public/image 8.png";
import grifoImg from "../../public/Image 5.png";

export const billingDetailsFormFields = [
  {
    id: 1,
    type: "text",
    name: "firstName",
    label: "First Name",
  },
  {
    id: 2,
    type: "text",
    name: "lastName",
    label: "Last Name",
  },
  {
    id: 3,
    type: "text",
    name: "companyName",
    label: "Company Name (Optional)",
  },
  {
    id: 4,
    type: "select",
    name: "country",
    options: [
      "United States",
      "Canada",
      "United Kingdom",
      "Australia",
      "Germany",
    ],
    label: "Country / Region",
  },
  {
    id: 5,
    type: "text",
    name: "streetAddress",
    label: "Street Address",
  },
  {
    id: 6,
    type: "text",
    name: "zipCode",
    label: "ZIP Code",
  },
  {
    id: 7,
    type: "text",
    name: "phone",
    label: "Phone",
  },
  {
    id: 8,
    type: "email",
    name: "email",
    label: "Email",
  },
];

export const navLinks = [
  {
    href: "/",
    label: "Home",
  },
  {
    href: "/shop",
    label: "Shop",
  },
  {
    href: "/about",
    label: "About",
  },
  {
    href: "/contact",
    label: "Contact",
  },
];

export const mockData = [
  {
    id: "1",
    name: "Syltherine",
    shortSynopsis: "Stylish cafe chair",
    price: 42,
    priceWithoutDiscount: 65,
    isDiscounted: true,
    discountPercentage: 30,
    isNew: false,
    previewImage: syltherineImg,
  },
  {
    id: "2",
    name: "Leviosa",
    shortSynopsis: "Stylish cafe chair",
    price: 42,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: false,
    previewImage: leviosaImg,
  },
  {
    id: "3",
    name: "Lolito",
    shortSynopsis: "Luxury big sofa",
    price: 150,
    priceWithoutDiscount: 300,
    isDiscounted: true,
    discountPercentage: 50,
    isNew: false,
    previewImage: lolitoImg,
  },
  {
    id: "4",
    name: "Respira",
    shortSynopsis: "Outdoor bar table and stool",
    price: 20,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: false,
    previewImage: respiraImg,
  },
  {
    id: "5",
    name: "Grifo",
    shortSynopsis: "Night lamp",
    price: 20,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: false,
    previewImage: grifoImg,
  },
  {
    id: "6",
    name: "Muggo",
    shortSynopsis: "Small mug",
    price: 10,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: true,
    previewImage: muggoImg,
  },
  {
    id: "7",
    name: "Pinkgy",
    shortSynopsis: "Cute bed set",
    price: 250,
    priceWithoutDiscount: 500,
    isDiscounted: true,
    discountPercentage: 50,
    isNew: false,
    previewImage: pingkyImg,
  },
  {
    id: "8",
    name: "Potty",
    shortSynopsis: "Minimalist pot",
    price: 200,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: true,
    previewImage: pottyImg,
  },
  {
    id: "9",
    name: "Syltherine",
    shortSynopsis: "Stylish cafe chair",
    price: 42,
    priceWithoutDiscount: 65,
    isDiscounted: true,
    discountPercentage: 30,
    isNew: false,
    previewImage: syltherineImg,
  },
  {
    id: "10",
    name: "Leviosa",
    shortSynopsis: "Stylish cafe chair",
    price: 42,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: false,
    previewImage: leviosaImg,
  },
  {
    id: "11",
    name: "Lolito",
    shortSynopsis: "Luxury big sofa",
    price: 150,
    priceWithoutDiscount: 300,
    isDiscounted: true,
    discountPercentage: 50,
    isNew: false,
    previewImage: lolitoImg,
  },
  {
    id: "12",
    name: "Respira",
    shortSynopsis: "Outdoor bar table and stool",
    price: 20,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: false,
    previewImage: respiraImg,
  },
  {
    id: "13",
    name: "Grifo",
    shortSynopsis: "Night lamp",
    price: 20,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: false,
    previewImage: grifoImg,
  },
  {
    id: "14",
    name: "Muggo",
    shortSynopsis: "Small mug",
    price: 10,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: true,
    previewImage: muggoImg,
  },
  {
    id: "15",
    name: "Pinkgy",
    shortSynopsis: "Cute bed set",
    price: 250,
    priceWithoutDiscount: 500,
    isDiscounted: true,
    discountPercentage: 50,
    isNew: false,
    previewImage: pingkyImg,
  },
  {
    id: "16",
    name: "Potty",
    shortSynopsis: "Minimalist pot",
    price: 200,
    priceWithoutDiscount: null,
    isDiscounted: false,
    discountPercentage: null,
    isNew: true,
    previewImage: pottyImg,
  },
];

export const customFiltersForFiltering = [
  "sofa",
  "mug",
  "lamp",
  "chair",
  "table",
];
